CONFIG_LTO=y
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

CONFIG_USB_DEVICE_STACK_NEXT=n

CONFIG_USB_DEVICE_GS_USB_TIMESTAMP=y
CONFIG_USB_DEVICE_GS_USB_TERMINATION=n
CONFIG_USB_DEVICE_GS_USB_MAX_CHANNELS=1
CONFIG_USB_DEVICE_GS_USB_TIMESTAMP_SOF=y
CONFIG_USB_DEVICE_GS_USB_IDENTIFICATION=y

# CONFIG_USB_DEVICE_GS_USB_MAX_PACKET_SIZE=512
# CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
